# Generated by Django 2.0.1 on 2018-01-20 21:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180120_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to=accounts.models.image_upload_path),
        ),
    ]
