# Generated by Django 2.0.1 on 2018-02-21 01:11

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180218_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
