# Generated by Django 2.0.1 on 2018-02-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180220_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(help_text='ex: mm/dd/yyyy'),
        ),
    ]
